export const FETCH_ALL = 'FETCH_ALL'
export const CREATE = 'CREATE'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const DELETE = 'DELETE'
export const FETCH_POST = 'FETCH_POST'